In [1]:
import numpy as np
# I which to create an array with size = size
size= 20
scalar = 3.14
#Filled with zeros:
print(np.zeros(size))
#Filled with ones:
print(np.ones(size))
#Filles with a set scalar:
print(np.full(size,scalar))

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[3.14 3.14 3.14 3.14 3.14 3.14 3.14 3.14 3.14 3.14 3.14 3.14 3.14 3.14
 3.14 3.14 3.14 3.14 3.14 3.14]

In [2]:
#turn a list into an np array
list =[1,2,3,4,5]
array= np.array(list)
print(array)

[1 2 3 4 5]

In [3]:
#print array 1st element
print(array[0])

1

In [4]:
#replace arrays 1st elment
array[0]=6
print(array)

[6 2 3 4 5]

In [5]:
# arange creates a range of numbers - it works like the Python function range, except instead of an iterator it gives us a NumPy array. 
print(np.arange(2,10,2)) # step=2 , range_end is excluding

[2 4 6 8]

In [6]:
# linspace is a little diferent, instead of specifying the step, you specify how many equidistant data points you want
print(np.linspace(2,10,5)) # also doesnt exclude the range_end
print(np.linspace(2,10,9))

[ 2.  4.  6.  8. 10.]
[ 2.  3.  4.  5.  6.  7.  8.  9. 10.]

In [7]:
# Multidimension arrays
sizexx=5
sizeyy=2
print(np.zeros((sizexx,sizeyy)))

[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]

In [8]:
#matrices from lists
n = np.array([
              [1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]
          ])

print(n[0,2])
#you can also replace an elements using the same methods as before
#-----------------
print(n[0]) #gives the 1st row
print(n[:,0])#gives the first column , the ":" kinda means "full range of rows"
#-----------------
#we can assign/ replace full rows and columns, in this case we replace the first row with the first column and viceversa
n[0]=n[:,0]
n[:,0] =[1,2,3]
print(n)

3
[1 2 3]
[1 4 7]
[[1 4 7]
 [2 5 6]
 [3 8 9]]

If we want to make the results reproducible - so that when you run this code you get the same numbers as I do - we can fix the random seed. These numbers are not really random, they are pseudorandom: they are generated by an algorithm, and we can set the seed of this generator. Then the sequence of numbers produced on my computer and on your computer will be the same.

In [9]:
# Numpy also generates random number arrays 
# matrix with 5 rows and 2 cols
np.random.seed(2)
rand= np.random.rand(5, 2) # ( between 0 and 1)
print(100*rand) # between 0 and 100
randn= np.random.randn(5, 2) # normal distribution mean=0, standdev=1
print(randn)
rand_int= np.random.randint(low=0, high=100, size=(5, 2)) # random integers between 0 and 99
print(rand_int)

[[43.59949021  2.59262318]
 [54.96624779 43.53223926]
 [42.03678021 33.0334821 ]
 [20.4648634  61.92709664]
 [29.96546737 26.68272751]]
[[ 0.55145404  2.29220801]
 [ 0.04153939 -1.11792545]
 [ 0.53905832 -0.5961597 ]
 [-0.0191305   1.17500122]
 [-0.74787095  0.00902525]]
[[83 31]
 [66 80]
 [52 76]
 [50  4]
 [90 63]]

In [10]:
# element wise operations
a= np.random.randint(low=0, high=5, size=5) # random integers between 0 and 99
b= np.random.randint(low=0, high=5, size=5) # random integers between 0 and 99

print(a)
print(a+1)
print(a*2)
##
print(a)
print(b)
print(a+b)
print(a >=2)

[1 0 2 2 1]
[2 1 3 3 2]
[2 0 4 4 2]
[1 0 2 2 1]
[0 1 0 2 1]
[1 1 2 4 2]
[False False  True  True False]

In [11]:
# quais elementos de a sao maiores que os respetivos em b?
a[a > b]

array([1, 2])

In [12]:
# summarizing operations
print(a.min())
print(a.mean())
print(a.std())
print(a.sum())

0
1.2
0.7483314773547883
6

In [13]:
#Vetor multiplication (dot product)
print(a* b) # this is not dot product
print(a.dot(b))

[0 0 0 4 1]
5

In [16]:
# dot product tambem funciona com matrizes
U = np.array([
        [2, 4, 5, 6, 1],
        [1, 2, 1, 2, 1],
        [3, 1, 2, 1, 1],
    ])
print(a)
print(U.dot(a))

[1 0 2 2 1]
[25  8 10]

In [17]:
U = np.array([
        [2, 4, 5],
        [1, 2, 1],
    ])
V = np.array([
        [2, 4],
        [1, 2],
        [3, 1],
    ])

U.dot(V)

array([[23, 21],
       [ 7,  9]])

The identity matrix is a square matrix where on the diagonal we have ones, and zeros everywhere else:

In [28]:
I = np.eye(3)
U = np.array([
        [2, 4, 5],
        [1, 2, 1],
        [3, 1, 2],
    ])
print(U.dot(I))
print(I.dot(U))

[[2. 4. 5.]
 [1. 2. 1.]
 [3. 1. 2.]]
[[2. 4. 5.]
 [1. 2. 1.]
 [3. 1. 2.]]

The identity matrix is useful for explaining what a matrix inverse is. Let's say we have a matrix A. The inverse of A, usually written A⁻¹, is a matrix such that when we multiply it by A, we get I. Just like with scalars (1/a)*a=1 for a!=0

In [29]:
U_inv = np.linalg.inv(U) # linear algebra package 
U_inv

array([[-0.2       ,  0.2       ,  0.4       ],
       [-0.06666667,  0.73333333, -0.2       ],
       [ 0.33333333, -0.66666667, -0.        ]])

U⁻¹U=UU⁻¹=I

In [30]:
U_inv.dot(U)

array([[ 1.00000000e+00, -5.55111512e-17,  0.00000000e+00],
       [ 2.77555756e-17,  1.00000000e+00, -5.55111512e-17],
       [ 0.00000000e+00,  0.00000000e+00,  1.00000000e+00]])

In [31]:
U.dot(U_inv)

array([[ 1.00000000e+00,  3.33066907e-16,  0.00000000e+00],
       [-5.55111512e-17,  1.00000000e+00,  0.00000000e+00],
       [ 0.00000000e+00,  0.00000000e+00,  1.00000000e+00]])

In [35]:
import pandas as pd
data = [
    ['Nissan', 'Stanza', 1991, 138, 4, 'MANUAL', 'sedan', 2000],
    ['Hyundai', 'Sonata', 2017, None, 4, 'AUTOMATIC', 'Sedan', 27150],
    ['Lotus', 'Elise', 2010, 218, 4, 'MANUAL', 'convertible', 54990],
    ['GMC', 'Acadia',  2017, 194, 4, 'AUTOMATIC', '4dr SUV', 34450],
    ['Nissan', 'Frontier', 2017, 261, 6, 'MANUAL', 'Pickup', 32340],
]

columns = [
    'Make', 'Model', 'Year', 'Engine HP', 'Engine Cylinders',
    'Transmission Type', 'Vehicle_Style', 'MSRP'
]

df = pd.DataFrame(data, columns=columns)

df

,Make,Model,Year,Engine HP,Engine Cylinders,Transmission Type,Vehicle_Style,MSRP
0,Nissan,Stanza,1991,138.0,4,MANUAL,sedan,2000
1,Hyundai,Sonata,2017,NaN,4,AUTOMATIC,Sedan,27150
2,Lotus,Elise,2010,218.0,4,MANUAL,convertible,54990
3,GMC,Acadia,2017,194.0,4,AUTOMATIC,4dr SUV,34450
4,Nissan,Frontier,2017,261.0,6,MANUAL,Pickup,32340

In [ ]:
data2 = [
    {
        "Make": "Nissan",
        "Model": "Stanza",
        "Year": 1991,
        "Engine HP": 138.0,
        "Engine Cylinders": 4,
        "Transmission Type": "MANUAL",
        "Vehicle_Style": "sedan",
        "MSRP": 2000
    },
    {
        "Make": "Hyundai",
        "Model": "Sonata",
        "Year": 2017,
        "Engine HP": None,
        "Engine Cylinders": 4,
        "Transmission Type": "AUTOMATIC",
        "Vehicle_Style": "Sedan",
        "MSRP": 27150
    }
    # ...
]

df2 = pd.DataFrame(data2, columns=columns)

df2.head(n=2)

,Make,Model,Year,Engine HP,Engine Cylinders,Transmission Type,Vehicle_Style,MSRP
0,Nissan,Stanza,1991,138.0,4,MANUAL,sedan,2000
1,Hyundai,Sonata,2017,NaN,4,AUTOMATIC,Sedan,27150

In [37]:
print(df.Make)
print(df["Make"])

0     Nissan
1    Hyundai
2      Lotus
3        GMC
4     Nissan
Name: Make, dtype: str
0     Nissan
1    Hyundai
2      Lotus
3        GMC
4     Nissan
Name: Make, dtype: str

In [38]:
df[['Make', 'Model', 'MSRP']]

      Make     Model   MSRP
0   Nissan    Stanza   2000
1  Hyundai    Sonata  27150
2    Lotus     Elise  54990
3      GMC    Acadia  34450
4   Nissan  Frontier  32340

In [44]:
df['id'] = [1, 2, 3, 4, 5]
df

,Make,Model,Year,Engine HP,Engine Cylinders,Transmission Type,Vehicle_Style,MSRP,id
0,Nissan,Stanza,1991,138.0,4,MANUAL,sedan,2000,1
1,Hyundai,Sonata,2017,NaN,4,AUTOMATIC,Sedan,27150,2
2,Lotus,Elise,2010,218.0,4,MANUAL,convertible,54990,3
3,GMC,Acadia,2017,194.0,4,AUTOMATIC,4dr SUV,34450,4
4,Nissan,Frontier,2017,261.0,6,MANUAL,Pickup,32340,5

In [41]:
#loc acesses data by location ( of the index on the left)
df.loc[1]

Make                   Hyundai
Model                   Sonata
Year                      2017
Engine HP                  NaN
Engine Cylinders             4
Transmission Type    AUTOMATIC
Vehicle_Style            Sedan
MSRP                     27150
id                           2
Name: 1, dtype: object

In [45]:
del df['id']
df

,Make,Model,Year,Engine HP,Engine Cylinders,Transmission Type,Vehicle_Style,MSRP
0,Nissan,Stanza,1991,138.0,4,MANUAL,sedan,2000
1,Hyundai,Sonata,2017,NaN,4,AUTOMATIC,Sedan,27150
2,Lotus,Elise,2010,218.0,4,MANUAL,convertible,54990
3,GMC,Acadia,2017,194.0,4,AUTOMATIC,4dr SUV,34450
4,Nissan,Frontier,2017,261.0,6,MANUAL,Pickup,32340

In [49]:
df.index = ['a', 'b', 'c', 'd', 'e'] # da para mudar o index pra letras
df
# now you can only loc['a'] 
# but can still use the original index with iloc
print(df.loc['b'])
print(df.iloc[1])

Make                   Hyundai
Model                   Sonata
Year                      2017
Engine HP                  NaN
Engine Cylinders             4
Transmission Type    AUTOMATIC
Vehicle_Style            Sedan
MSRP                     27150
Name: b, dtype: object
Make                   Hyundai
Model                   Sonata
Year                      2017
Engine HP                  NaN
Engine Cylinders             4
Transmission Type    AUTOMATIC
Vehicle_Style            Sedan
MSRP                     27150
Name: b, dtype: object

In [50]:
df = df.reset_index(drop=True)
df.index

RangeIndex(start=0, stop=5, step=1)

In [51]:
#element wise operations
df['Engine HP'] * 2

0    276.0
1      NaN
2    436.0
3    388.0
4    522.0
Name: Engine HP, dtype: float64

In [52]:
df['Year'] >= 2015

0    False
1     True
2    False
3     True
4     True
Name: Year, dtype: bool

In [53]:
#filtrar a df
df[df['Make'] == 'Nissan']

,Make,Model,Year,Engine HP,Engine Cylinders,Transmission Type,Vehicle_Style,MSRP
0,Nissan,Stanza,1991,138.0,4,MANUAL,sedan,2000
4,Nissan,Frontier,2017,261.0,6,MANUAL,Pickup,32340

In [55]:
df[(df['Make'] == 'Nissan') & (df['Year'] >= 2015)]

,Make,Model,Year,Engine HP,Engine Cylinders,Transmission Type,Vehicle_Style,MSRP
4,Nissan,Frontier,2017,261.0,6,MANUAL,Pickup,32340

In [ ]:
# string operations
df['Vehicle_Style'].str.lower()

0          sedan
1          sedan
2    convertible
3        4dr suv
4         pickup
Name: Vehicle_Style, dtype: str

In [57]:
df['Vehicle_Style'].str.replace(' ', '_')

0          sedan
1          Sedan
2    convertible
3        4dr_SUV
4         Pickup
Name: Vehicle_Style, dtype: str

In [59]:
#column wise operations
print(df.MSRP.mean())
print(df.MSRP.max() )

30186.0
54990

In [60]:
df.MSRP.describe()

count        5.000000
mean     30186.000000
std      18985.044904
min       2000.000000
25%      27150.000000
50%      32340.000000
75%      34450.000000
max      54990.000000
Name: MSRP, dtype: float64

In [61]:
df.describe().round(2)

          Year  Engine HP  Engine Cylinders      MSRP
count     5.00       4.00              5.00      5.00
mean   2010.40     202.75              4.40  30186.00
std      11.26      51.30              0.89  18985.04
min    1991.00     138.00              4.00   2000.00
25%    2010.00     180.00              4.00  27150.00
50%    2017.00     206.00              4.00  32340.00
75%    2017.00     228.75              4.00  34450.00
max    2017.00     261.00              6.00  54990.00

In [62]:
#unique values per columns
df.nunique()

Make                 4
Model                5
Year                 3
Engine HP            4
Engine Cylinders     2
Transmission Type    2
Vehicle_Style        5
MSRP                 5
dtype: int64

In [65]:
df.isnull().sum()

Make                 0
Model                0
Year                 0
Engine HP            1
Engine Cylinders     0
Transmission Type    0
Vehicle_Style        0
MSRP                 0
dtype: int64

In [66]:
df.groupby('Transmission Type').MSRP.max()

Transmission Type
AUTOMATIC    34450
MANUAL       54990
Name: MSRP, dtype: int64

In [67]:
# want to see underlying numpy arrays?
df.MSRP.values

array([ 2000, 27150, 54990, 34450, 32340])

In [68]:
df.to_dict(orient='records')

[{'Make': 'Nissan',
  'Model': 'Stanza',
  'Year': 1991,
  'Engine HP': 138.0,
  'Engine Cylinders': 4,
  'Transmission Type': 'MANUAL',
  'Vehicle_Style': 'sedan',
  'MSRP': 2000},
 {'Make': 'Hyundai',
  'Model': 'Sonata',
  'Year': 2017,
  'Engine HP': nan,
  'Engine Cylinders': 4,
  'Transmission Type': 'AUTOMATIC',
  'Vehicle_Style': 'Sedan',
  'MSRP': 27150},
 {'Make': 'Lotus',
  'Model': 'Elise',
  'Year': 2010,
  'Engine HP': 218.0,
  'Engine Cylinders': 4,
  'Transmission Type': 'MANUAL',
  'Vehicle_Style': 'convertible',
  'MSRP': 54990},
 {'Make': 'GMC',
  'Model': 'Acadia',
  'Year': 2017,
  'Engine HP': 194.0,
  'Engine Cylinders': 4,
  'Transmission Type': 'AUTOMATIC',
  'Vehicle_Style': '4dr SUV',
  'MSRP': 34450},
 {'Make': 'Nissan',
  'Model': 'Frontier',
  'Year': 2017,
  'Engine HP': 261.0,
  'Engine Cylinders': 6,
  'Transmission Type': 'MANUAL',
  'Vehicle_Style': 'Pickup',
  'MSRP': 32340}]